# Merges every per-PI bibliography in _bibliography/pi/*.bib into a single
# _bibliography/schema.bib, which jekyll-scholar reads (see _config.yml: scholar.bibliography).
#
# PIs only ever edit their own _bibliography/pi/<name>.bib file and commit it.
# The merged schema.bib is generated at build time and should NOT be edited by hand
# (it is listed in .gitignore).
module Schema
  class BibMerger < Jekyll::Generator
    priority :highest
    safe false

    def generate(site)
      pi_dir  = File.join(site.source, '_bibliography', 'pi')
      out_file = File.join(site.source, '_bibliography', 'schema.bib')
      return unless Dir.exist?(pi_dir)

      files = Dir.glob(File.join(pi_dir, '*.bib')).sort
      merged = +"% AUTO-GENERATED by _plugins/merge_bib.rb — do not edit by hand.\n"
      merged << "% Source files: _bibliography/pi/*.bib\n\n"
      files.each do |f|
        merged << "% ============================================================\n"
        merged << "% Source: #{File.basename(f)}\n"
        merged << "% ============================================================\n"
        merged << File.read(f)
        merged << "\n\n"
      end

      File.write(out_file, merged)
      Jekyll.logger.info "SCHEMA:", "merged #{files.size} PI bib file(s) -> _bibliography/schema.bib"
    end
  end
end
